### ISSUE TITLE
See which pilots are watching robot

### ISSUE THREAD

**Issue by olawlor** [robotmoose/robotmoose#12]
The frontend should display which pilots are watching your robot while you're driving.

(Low-priority feature request, for AFTER workshop)

**Comment by mrmoss** [comment]
I have this working...however it breaks the current implementation of the gruveo dialback feature on the backend. I currently just don't know which pilot to take as the video.

I'm generating a uuid for each pilot and keep track of each of their heartbeats...so this shouldn't be too hard to get to work with the gruveo side of things...

This isn't pushed yet since it breaks the gruveo feature...

**Comment by Arsh25** [comment]
How are you handling which pilot gets to drive the robot? I think the easiest way would be to connect back to the pilot driving.

**Comment by mrmoss** [comment]
That's not really a thing, any pilot can drive. My current thinking is give
the camera to the oldest pilot. Once that pilot leaves, give the camera to
the next oldest pilot.

**Comment by Arsh25** [comment]
Isn't the whole point of having multiple pilots is so that some can watch the robot (sensors) while one commands without having watchers overwrite the commander?

**Comment by mrmoss** [comment]
This already works as long as two pilots aren't driving the robot at the
same time (honor system style).
