### ISSUE TITLE
Simplify loading map images

### ISSUE THREAD

**Issue by Michaeasmith** [robotmoose/robotmoose#33]
Implement easier way to load map images of any scale, tied to a specific robot.

**Comment by Michaeasmith** [comment]
I rewrote the code so that it is now possible to use a map of any size. The map creation function takes a JSON of name, width, and height.

There are two questions here that we should probably answer as a group before implementing anything:

1) How should maps be uploaded? Should anyone be able to upload a map image, or should we have a robotmoose page accessible only to teachers/facilitators where images can be uploaded?

2) How should users access the maps? Should they be robot-specific? Should there be some example map images accessible to any robot?

**Comment by mrmoss** [comment]
My thoughts:
- I'm still in favor of client side uploads (we host a few "official" maps, any other map is just an image that is uploaded).
- I know that not everyone agrees with this, so I'd be most comfortable with just allowing people with server access to upload images (no user portal at all)...because that's how we end up with awesome new administrators from Romania...
- Ultimately, the best worst-case scenario, we could make a new top level path in superstar for images and store then in binary format. Then we could make a simple web side form to upload images...

**Comment by Michaeasmith** [comment]
![to_infinity](https://cloud.githubusercontent.com/assets/13650684/17082032/69a9049e-511b-11e6-80e4-f2d11ae84b63.png)

![moon_landing](https://cloud.githubusercontent.com/assets/13650684/17082031/5e768efc-511b-11e6-9476-122490c495d1.png)

I have successfully landed a roomba sim on the moon.

In other news, I added a client-side upload map image feature. It would be great if someone could test it and/or give feedback about the UI.
