### ISSUE TITLE
Frontend top bar issues.

### ISSUE THREAD

**Issue by mrmoss** [robotmoose/robotmoose#73]
Frontend top bar doesn't react as expected. When the width of the screen is smaller than the bar, it gets bigger and doorways can go on top of it.

**Comment by mrmoss** [comment]
When window starts small the menu moves all the windows about:
<img width="675" alt="screen shot 2016-06-28 at 7 03 28 pm" src="https://cloud.githubusercontent.com/assets/1828563/16439254/09a02148-3d63-11e6-9f6f-22d7a3255b9b.png">

The top bar also does weird things if it starts small and then is enlarged again:
<img width="690" alt="screen shot 2016-06-28 at 7 00 48 pm" src="https://cloud.githubusercontent.com/assets/1828563/16439218/b881ffe8-3d62-11e6-8263-5ed4b647f5ba.png">

**Comment by raikaDial** [comment]
Ah, thought I fixed that. Where do you define the style for those buttons?

**Comment by mrmoss** [comment]
All in robot_menu.js.

**Comment by raikaDial** [comment]
As far as I can tell, the buttons were being messed up because doorways set the height of the menu bar to the height of the menu offset, which was not the ideal value when the menu was collapsed. I hacked the correct behavior by setting a static height for the menu bar, but an ideal solution may be to switch from nav-tabs that have their height reduced to a button type.

**Comment by mrmoss** [comment]
Feel free to completely swap out that system with whatever you think is
best.

**Comment by mrmoss** [comment]
Closing this in lieu of a new menu system in #116.
