### ISSUE TITLE
Separate giant repo into several small repos?

### ISSUE THREAD

**Issue by mrmoss** [robotmoose/robotmoose#84]
Should we?

Is there a way to transfer history for certain files to another repo? It'd be nice not to rebase...if possible...

**Comment by FineTralfazz** [comment]
This would make the test/deployment stuff that @arcshock and I are working on much easier, and reduce the number of unnecessary merges/rebases. Strong support from me.

**Comment by FineTralfazz** [comment]
Also, here's how to split it into multiple repos while maintaining history: https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/

**Comment by mrmoss** [comment]
I'm down then...not that my decision pulls any weight... @olawlor?

**Comment by olawlor** [comment]
Here's the challenge: we want to make our stuff really easy to access and use, and multiple repos makes it harder for users to collect everything they need.  For example, if you split up superstar and the C++ backend repos, they both depend on some shared network include files, so that'd go into a third repo.  A customer (who inevitably will need a local superstar at some point, for example for testing) then needs to clone and pull three separate repos, and we all enjoy the festival of version mismatch errors when they've inevitably done a pull on two of the three.

The big parts of the project include:
1. Superstar
2. C++ backend
3. Chromeapp backend
4. Web robot piloting frontend (javascript, css, a few index.html files)
5. Other web content, like pictures and tutorials
6. Hardware design files, like LAYLA OpenSCAD/STL files
7. Documentation, like Create2 interface spec

The first four are all tiny, a few megs, and also really tightly coupled.  Adding a feature like chat can touch frontend, superstar, and backend (ideally both C++ and chrome app).  

The last three are bigger (a few hundred megs) and less coupled to each other and the rest of the project.  I could see an argument for splitting those out, maybe into:
- robotmoose/robotmoose: 1-4 above.  Main source code distribution, and bare-bones web page.
- robotmoose/web: remainder of the web content, like tutorials and screenshots and such.
- robotmoose/hardware: circuit designs, debug firmware for new boards, 3D printer CAD part files for quizbot and layla, documentation.

But this is a pretty big change, and will mess up any un-pushed code people have, so we should discuss it at our Friday meeting and make sure everybody's onboard...

**Comment by FineTralfazz** [comment]
Yeah, that's a good point. git submodules can help with some of the problem, but they're not a perfect solution.

**Comment by Arsh25** [comment]
Final decision is to have 2 repositories:
1.  robotmoose/robotmoose: All software related files 
2. robotmoose/hardware: All hardware related files
   - Schematics and boards
   - Any related firmware 
   - CAD files

**Comment by mrmoss** [comment]
So I'm ready to rebase...literally do git rebase master and git push...

**Comment by mrmoss** [comment]
In case it wasn't obvious, do not delete ANY history.

**Comment by olawlor** [comment]
I'd definitely prefer to not remove history during the shift, but if that's not possible or too hard, we should have a robotmoose/archive with the old commit messages and version history available.

**Comment by computations** [comment]
The currently, everything is set up to do the swap. On Wednesday, I will replace the master branch with proposed_master (Doing this Wednesday, is due to the 4th coming up). Any commits to master since todays split will be sorted into either the hardware branch, or the proposed master before swapping. As for the old content, I will put that in a new repo called archive. 

Use this time to tell me that some files should be in one directory or another, or to tell me that I did something wrong, or to generally curse my name. I will get to those comments on Monday, when I am back in town.

**Comment by FineTralfazz** [comment]
[I set up a backup repo in case anything goes wrong. Hopefully we don't need it.](https://github.com/FineTralfazz/Chris-Baileys-Home-for-Endangered-Moose)

**Comment by computations** [comment]
The swap has been made, people might need to pull the new repo in order to commit any changes. The old repo, pre-fracture, is at https://github.com/robotmoose/archive. We should keep that repo read only, so that we don't have to do weird cherry picking when people push to the wrong repo.
