### ISSUE TITLE
Test server javascript is broken

### ISSUE THREAD

**Issue by raikaDial** [robotmoose/robotmoose#92]
Somewhere in the test server javascript code the code is broken, because most of the UI elements no longer function. I rolled back my local repo and tested until it was fixed. This commit https://github.com/robotmoose/robotmoose/commit/9d7402bdea60757864c94a62efd9ed58bfa8d9bb seems to be the culprit. @mrmoss

**Comment by Arsh25** [comment]
That commit was when the new multiple superstar paths syntax was introduced. My guess is the doorways don;t work because of something that the new networking protocol messed up.

**Comment by mrmoss** [comment]
Nope, this is because I commented out the try/catches in superstar.js...so
something is requesting something that is not a json object and actually
throwing instead of being saved by the superstar function...

**Comment by Arsh25** [comment]
Seems to be some malformed json in the new multiple set and get system. 

![selection_021](https://cloud.githubusercontent.com/assets/3912597/16432609/31d7ba80-3d32-11e6-83b4-42707d20fc2a.png)

**Comment by mrmoss** [comment]
I'm not getting any errors...

**Comment by Arsh25** [comment]
They are no errors in the console, the requests are coming back with a malformed JSON object as shown above

**Comment by mrmoss** [comment]
Malformed JSON objects in Chrome show up in the console (not as an error, but console.log because superstar.js saves it).

The whole "multiple get" thing isn't new. It's been there for a long time (I added it to the frontend, but the backend has had it for a long time).

I did move chat to the multiple get request thing. The chat system isn't using JSON objects, so it isn't decoding correctly. If the chat history was empty, the multiple get system makes it an empty object. I was testing on a stock robot that had no chat history...hence why it worked.
